import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from '@/components/Navbar';
import { AuthProvider } from "@/context/AuthContext";
import { Toaster } from "@/components/ui/toaster";
import BottomNavbar from "@/components/MobileComponent/Navbar";
import MobileNavbar from "@/components/MobileComponent/MobileNavbar";

  


const geistSans = Geist({
  variable: "--font-geist-sans", 
  subsets: ["latin"],  
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "SupaBetos",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  return (
    <html lang="en">
     
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
      {/* <AuthProvider> */}
      <Navbar />
      <div className="relative block sm:hidden">
  <BottomNavbar />
</div>


                       {children}
                       <Toaster />

                       {/* </AuthProvider> */}
      </body>
    </html> 
  );
}
